version: "3.4"
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - /home/mservage/data/mysql:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - my_network
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    volumes:
      - /home/mservage/data/html:/var/www/html
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - my_network
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - /home/mservage/data/html:/var/www/html
    ports:
      - 443:443
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - my_network
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
networks:
  my_network: {}
