version: "3.4"
services:
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - my_network
  wordpress:
    build:
      context: ./requirements/wordpress
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - my_network
networks:
  my_network: {}